const data = ["Select Subject",
"Registration - Auction Bidder",
"Registration - Password Not Received",
"Login - Failed to open Websigner Message/ JAVA issues",
"Login - Other Issues",
"System Settings / Browser Settings", 
"Change My Digital Signing Certificate", 
"Mapping of Bank Account", 
"Using SBI Corporate Account for E-Auction", 
"Submission of Bids and other Related activities", 
"Miscellaneous", 
"Suggestions",
"Registration - New Vendor",
"Change Primary User",
"Bidding - Online Payment of EMD / TDC",
"Bidding - Uploading of Documents",
"Bidding - Final Submission of Bids",
"Tender Tabulation",
"Bidding - Other Issues",
"DM - Dispatch Memo",
"IC - Inspection Certificate",
"NCR - NON CONFORMITY REPORT",
"Registration - New Vendor",
"Registration - New Contractor",
,"Change Primary user",
"Bidding - Uploading of Document",
"Bidding - Final submission of Bids",
"Reverse Auction Bidding",
"Bidding - Other issues",
"Tender Tabulation",
"DM - Dispatch Memo",
"IC - Inspection Certificate",
"NCR - NON-CONFORMITIY REPORT",
"Before Login Issue",
"After Login Issue"
]

export default data;